version: "3"

services:
  web:
    ports:
      - 80:80

  moodle:
    volumes:
      - ./3.7.6/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: [db]
    volumes:
      - /sessions
    networks:
      - frontend
      - backend
    ports:
      - 82:80
